version: '3'
services:
  ndash:
    build: ./
    environment:
      - GRAPHQL_ENDPOINT=http://localhost:4000
    ports:
      - 3000:3000
    volumes:
      - ./:/usr/src
      - /usr/src/node_modules
